import {
  Cherry,
  Spade,
  CircleDot,
  Dices,
  Circle,
  Bomb,
  TrendingUp,
  PieChart,
  ArrowUpDown,
  Hash,
  KeyRound,
  Coins,
  Ticket,
  Gem,
  Club,
  Sparkles,
  Lock,
  type LucideIcon,
} from "lucide-react";
import type { GameType } from "./store";

export const GAME_LABELS: Record<GameType, string> = {
  slots: "Slots",
  blackjack: "Blackjack",
  roulette: "Roulette",
  dice: "Dice",
  plinko: "Plinko",
  mines: "Mines",
  crash: "Crash",
  wheel: "Wheel of Fortune",
  hilo: "Hi-Lo",
  keno: "Keno",
  coinflip: "Coin Flip",
  scratch: "Scratch Card",
  baccarat: "Baccarat",
  poker: "Five-Card Draw",
  pachinko: "Pachinko",
  ownerVault: "Owner's Vault",
  ownerSafe: "Owner's Safe",
};

export const GAME_ROUTES: Record<GameType, string> = {
  slots: "/slots",
  blackjack: "/blackjack",
  roulette: "/roulette",
  dice: "/dice",
  plinko: "/plinko",
  mines: "/mines",
  crash: "/crash",
  wheel: "/wheel",
  hilo: "/hilo",
  keno: "/keno",
  coinflip: "/coin-flip",
  scratch: "/scratch",
  baccarat: "/baccarat",
  poker: "/poker",
  pachinko: "/pachinko",
  ownerVault: "/owner-vault",
  ownerSafe: "/owner-safe",
};

export const GAME_ICONS: Record<GameType, LucideIcon> = {
  slots: Cherry,
  blackjack: Spade,
  roulette: CircleDot,
  dice: Dices,
  plinko: Circle,
  mines: Bomb,
  crash: TrendingUp,
  wheel: PieChart,
  hilo: ArrowUpDown,
  keno: Hash,
  coinflip: Coins,
  scratch: Ticket,
  baccarat: Gem,
  poker: Club,
  pachinko: Sparkles,
  ownerVault: KeyRound,
  ownerSafe: Lock,
};
